/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JuegoDeNumeros.Pantallas;

import JuegoDeNumeros.ComparadorCompuAdivina;
import JuegoDeNumeros.Main;

/**
 *
 * @author SISTEMAS
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonaAdivina = new javax.swing.JToggleButton();
        CompuAdivina = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Adivinar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PersonaAdivina.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        PersonaAdivina.setForeground(new java.awt.Color(153, 0, 153));
        PersonaAdivina.setText("Persona Adivina");
        PersonaAdivina.setActionCommand("Persona \nAdivina");
        PersonaAdivina.setName(""); // NOI18N
        PersonaAdivina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonaAdivinaActionPerformed(evt);
            }
        });
        getContentPane().add(PersonaAdivina, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 190, 50));
        PersonaAdivina.getAccessibleContext().setAccessibleDescription("");

        CompuAdivina.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        CompuAdivina.setForeground(new java.awt.Color(153, 0, 153));
        CompuAdivina.setText("Computadora Adivina");
        CompuAdivina.setMaximumSize(new java.awt.Dimension(131, 25));
        CompuAdivina.setMinimumSize(new java.awt.Dimension(131, 25));
        CompuAdivina.setPreferredSize(new java.awt.Dimension(131, 25));
        CompuAdivina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompuAdivinaActionPerformed(evt);
            }
        });
        getContentPane().add(CompuAdivina, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 210, 50));

        jButton1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 90, 30));

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 204));
        jLabel2.setText("Bienvenido!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/81a7596f677c05990584afb0d275416e-gradiente-de-fondo-futurista.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 550, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompuAdivinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompuAdivinaActionPerformed
        //llama a la pantalla para que adivine la persona
        Compuadivina compuAdivin = new Compuadivina();
        compuAdivin.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_CompuAdivinaActionPerformed

    private void PersonaAdivinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonaAdivinaActionPerformed
//llama a la pantalla para que adivine la computadora
        Juego persAdivina = new Juego();
        persAdivina.setVisible(true);
        this.setVisible(false);
        Main.reset();
    }//GEN-LAST:event_PersonaAdivinaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompuAdivina;
    private javax.swing.JToggleButton PersonaAdivina;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
